#!/usr/bin/env bash

export DYALOG=$1
export MAXWS=128M WSPATH=$DYALOG/ws

cp $2 .coden.tio && echo "" >> .coden.tio

cat <<- . | "$DYALOG/dyalog" -script
	⎕PW←9999
	{}2⎕FIX'file://$(dirname "$BASH_SOURCE")/Run.dyalog'
	'.coden.tio'('R'Run '${@:4}')'$3'
.
